### ISSUE TITLE
Editor freezing up when trying to reference variables

### ISSUE THREAD

**Issue by kuribohlv9** [evasiongames/gameflow#55] opened 2018-09-07 09:06 UTC
When trying to access a variable through referencing a variable or game object,
![image](https://user-images.githubusercontent.com/6222094/45209640-c92b6f80-b28d-11e8-9032-9df11fa3a030.png)

The editor freezes up for a few seconds and doesn't respond. Clicking anywhere during this time will sometimes cause a crash and if not will show this error message.

![image](https://user-images.githubusercontent.com/6222094/45209497-78b41200-b28d-11e8-9932-d86da13bdc3e.png)

**Comment by evasiongames** [comment] 2018-09-07 10:40
Duplicate of #53

**Closed as completed by evasiongames** 2018-09-07 10:40 UTC
Labels: 2018.2
